CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    username VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL,
    password VARCHAR(255) NOT NULL,

    display_name VARCHAR(100),
    avatar_url VARCHAR(255),

    role VARCHAR(20) NOT NULL DEFAULT 'USER',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT ck_users_role CHECK (role IN ('USER', 'ADMIN'))
);


CREATE TABLE movies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    movielens_id BIGINT,
    tmdb_id BIGINT,

    title VARCHAR(500) NOT NULL,
    overview TEXT,
    genres VARCHAR(500),

    poster_path VARCHAR(300),
    backdrop_path VARCHAR(300),

    release_date DATE,
    original_language VARCHAR(10),
    runtime_minutes INTEGER,

    avg_rating DOUBLE PRECISION NOT NULL DEFAULT 0,
    rating_count BIGINT NOT NULL DEFAULT 0,

    baseline_avg_rating DOUBLE PRECISION DEFAULT 0,
    baseline_rating_count BIGINT DEFAULT 0,

    popularity DOUBLE PRECISION,
    vote_count INTEGER,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_movies_movielens_id UNIQUE (movielens_id)
);


CREATE UNIQUE INDEX idx_movie_tmdb_id
    ON movies (tmdb_id);

CREATE INDEX idx_movie_title
    ON movies (title);

CREATE INDEX idx_movie_release
    ON movies (release_date);

CREATE INDEX idx_movie_avg_rating
    ON movies (avg_rating);


CREATE TABLE ratings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id BIGINT NOT NULL,
    movie_id BIGINT NOT NULL,

    rating DOUBLE PRECISION NOT NULL,
    review TEXT,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    movielens_timestamp BIGINT,

    CONSTRAINT fk_ratings_user
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_ratings_movie
        FOREIGN KEY (movie_id)
        REFERENCES movies (id)
        ON DELETE CASCADE,

    CONSTRAINT uk_user_movie
        UNIQUE (user_id, movie_id),

    CONSTRAINT ck_rating_range
        CHECK (rating >= 0.5 AND rating <= 5.0)
);


CREATE INDEX idx_rating_user_id
    ON ratings (user_id);

CREATE INDEX idx_rating_movie_id
    ON ratings (movie_id);

CREATE INDEX idx_rating_value
    ON ratings (rating);

CREATE INDEX idx_rating_created_at
    ON ratings (created_at);